name: pgnniv_env
channels:
  - defaults
dependencies:
  - asttokens=2.0.5
  - blas=1.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2024.3.11
  - colorama=0.4.6
  - comm=0.2.1
  - contourpy=1.2.0
  - cycler=0.11.0
  - debugpy=1.6.7
  - decorator=5.1.1
  - exceptiongroup=1.2.0
  - executing=0.8.3
  - expat=2.5.0
  - fonttools=4.25.0
  - freetype=2.12.1
  - icc_rt=2022.1.0
  - icu=73.1
  - intel-openmp=2023.1.0
  - ipykernel=6.28.0
  - ipython=8.20.0
  - jedi=0.18.1
  - joblib=1.2.0
  - jpeg=9e
  - jupyter_client=8.6.0
  - jupyter_core=5.5.0
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang13=14.0.6
  - libdeflate=1.17
  - libffi=3.4.4
  - libpng=1.6.39
  - libpq=12.17
  - libsodium=1.0.18
  - libtiff=4.5.1
  - libwebp-base=1.3.2
  - lz4-c=1.9.4
  - matplotlib=3.8.0
  - matplotlib-base=3.8.0
  - matplotlib-inline=0.1.6
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - munkres=1.1.4
  - nest-asyncio=1.6.0
  - numpy-base=1.26.4
  - openjpeg=2.4.0
  - openssl=3.0.13
  - parso=0.8.3
  - pillow=10.2.0
  - pip=23.3.1
  - platformdirs=3.10.0
  - ply=3.11
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - pure_eval=0.2.2
  - pygments=2.15.1
  - pyparsing=3.0.9
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - python=3.10.14
  - python-dateutil=2.8.2
  - pywin32=305
  - pyzmq=25.1.2
  - qt-main=5.15.2
  - scikit-learn=1.3.0
  - scipy=1.12.0
  - setuptools=68.2.2
  - sip=6.7.12
  - six=1.16.0
  - sqlite=3.41.2
  - stack_data=0.2.0
  - tbb=2021.8.0
  - threadpoolctl=2.2.0
  - tk=8.6.12
  - tomli=2.0.1
  - tornado=6.3.3
  - traitlets=5.7.1
  - tzdata=2024a
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wcwidth=0.2.5
  - wheel=0.41.2
  - xz=5.4.6
  - zeromq=4.3.5
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - absl-py==2.1.0
      - astunparse==1.6.3
      - cachetools==5.3.3
      - certifi==2024.2.2
      - charset-normalizer==3.3.2
      - flatbuffers==24.3.25
      - gast==0.4.0
      - google-auth==2.29.0
      - google-auth-oauthlib==1.0.0
      - google-pasta==0.2.0
      - grpcio==1.62.1
      - h5py==3.10.0
      - idna==3.6
      - keras==2.14.0
      - libclang==18.1.1
      - markdown==3.6
      - markupsafe==2.1.5
      - memory-profiler==0.61.0
      - ml-dtypes==0.2.0
      - numpy==1.24.3
      - oauthlib==3.2.2
      - opt-einsum==3.3.0
      - packaging==24.0
      - protobuf==4.25.3
      - psutil==5.9.8
      - pyasn1==0.6.0
      - pyasn1-modules==0.4.0
      - requests==2.31.0
      - requests-oauthlib==2.0.0
      - rsa==4.9
      - tensorboard==2.14.1
      - tensorboard-data-server==0.7.2
      - tensorflow==2.14.0
      - tensorflow-estimator==2.14.0
      - tensorflow-intel==2.14.0
      - tensorflow-io-gcs-filesystem==0.31.0
      - termcolor==2.4.0
      - typing-extensions==4.5.0
      - urllib3==2.2.1
      - werkzeug==3.0.2
      - wrapt==1.14.1
